# Generated by Django 2.1.3 on 2018-11-26 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, help_text='品牌名称', max_length=65, verbose_name='品牌名称')),
                ('alias', models.CharField(default=None, help_text='品牌别名', max_length=65, verbose_name='品牌别名')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'brand信息',
                'verbose_name_plural': 'brand信息',
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, help_text='公司名称', max_length=65, verbose_name='公司名称')),
                ('alias', models.CharField(default=None, help_text='公司别名', max_length=65, verbose_name='公司别名')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'company信息',
                'verbose_name_plural': 'company信息',
                'db_table': 'company',
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companys', to='system_info.Company'),
        ),
    ]
