# Generated by Django 2.1.3 on 2018-11-26 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='频道名称', max_length=200, unique=True, verbose_name='频道名称')),
                ('alias', models.CharField(help_text='频道别名', max_length=200, verbose_name='频道别名')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
            ],
            options={
                'db_table': 'channel_name',
                'verbose_name': '频道名称信息',
                'verbose_name_plural': '频道名称信息',
            },
        ),
        migrations.CreateModel(
            name='ChannelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='类型名称', max_length=200, unique=True, verbose_name='类型名称')),
                ('alias', models.CharField(help_text='类型别名', max_length=200, verbose_name='类型别名')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
            ],
            options={
                'db_table': 'channel_type',
                'verbose_name': '频道类型信息',
                'verbose_name_plural': '频道类型信息',
            },
        ),
        migrations.AddField(
            model_name='channelname',
            name='classify',
            field=models.ForeignKey(help_text='频道类别', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channelnames', to='system_info.ChannelType', verbose_name='频道类别'),
        ),
    ]
