# Generated by Django 2.1.3 on 2018-11-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_info', '0003_channelname_chid'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelname',
            name='image',
            field=models.ImageField(help_text='频道图片', null=True, upload_to='system_info/std_channel/', verbose_name='频道图片'),
        ),
    ]
