# Generated by Django 2.1.3 on 2018-11-30 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_info', '0006_auto_20181130_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slave',
            options={'verbose_name': 'Slave信息', 'verbose_name_plural': 'Slave信息'},
        ),
    ]
