# Generated by Django 2.1.3 on 2018-12-05 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_info', '0007_auto_20181130_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliasChName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='频道名称', max_length=200, unique=True, verbose_name='频道名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
            ],
            options={
                'db_table': 'alias_channel',
                'verbose_name': '频道别名',
                'verbose_name_plural': '频道别名',
            },
        ),
        migrations.CreateModel(
            name='StdChName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_id', models.CharField(default=None, help_text='频道id', max_length=65, unique=True, verbose_name='频道id')),
                ('name', models.CharField(help_text='频道名称', max_length=200, verbose_name='频道名称')),
                ('image', models.ImageField(help_text='频道图片', null=True, upload_to='system_info/std_channel/', verbose_name='频道图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
            ],
            options={
                'db_table': 'std_channel',
                'verbose_name': '频道名称信息',
                'verbose_name_plural': '频道名称信息',
            },
        ),
        migrations.RemoveField(
            model_name='channelname',
            name='classify',
        ),
        migrations.DeleteModel(
            name='ChannelName',
        ),
        migrations.DeleteModel(
            name='ChannelType',
        ),
        migrations.AddField(
            model_name='aliaschname',
            name='std_ch',
            field=models.ForeignKey(help_text='频道别名表', on_delete=django.db.models.deletion.CASCADE, related_name='aliaschnames', to='system_info.StdChName', verbose_name='频道别名表'),
        ),
    ]
