# Generated by Django 2.1.3 on 2018-12-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_info', '0008_auto_20181205_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aliaschname',
            options={'ordering': ('name',), 'verbose_name': '频道别名', 'verbose_name_plural': '频道别名'},
        ),
        migrations.AlterModelOptions(
            name='stdchname',
            options={'ordering': ('name',), 'verbose_name': '频道名称信息', 'verbose_name_plural': '频道名称信息'},
        ),
        migrations.AlterField(
            model_name='stdchname',
            name='image',
            field=models.ImageField(blank=True, help_text='频道图片', null=True, upload_to='system_info/std_channel/', verbose_name='频道图片'),
        ),
    ]
