# Generated by Django 2.1.3 on 2018-12-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_info', '0009_auto_20181210_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stdchname',
            name='name',
            field=models.CharField(help_text='频道名称', max_length=200, unique=True, verbose_name='频道名称'),
        ),
    ]
