# Generated by Django 2.1.3 on 2018-11-27 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirmUploadImgStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(default=None, help_text='厂商名称', max_length=65, verbose_name='厂商名称')),
                ('img_num', models.IntegerField(default=None, help_text='图片数', verbose_name='图片数')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'FirmUploadImgStatistic信息',
                'verbose_name_plural': 'FirmUploadImgStatistic信息',
                'db_table': 'FirmUploadImgStatistic',
            },
        ),
        migrations.CreateModel(
            name='ModelStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(default=None, help_text='厂商名称', max_length=65, verbose_name='厂商名称')),
                ('model', models.CharField(default=None, help_text='型号', max_length=65, verbose_name='型号')),
                ('model_num', models.IntegerField(default=None, help_text='型号数', verbose_name='型号数')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('firmUploadImgStatistic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmUploadImgStatistic_id', to='statistics_info.FirmUploadImgStatistic')),
            ],
            options={
                'verbose_name': 'modelStatistic信息',
                'verbose_name_plural': 'modelStatistic信息',
                'db_table': 'modelStatistic',
            },
        ),
        migrations.CreateModel(
            name='SlaveStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default=None, help_text='公司名称', max_length=65, verbose_name='公司名称')),
                ('did_num', models.IntegerField(default=None, help_text='设备数', verbose_name='设备数')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'slaveStatistic信息',
                'verbose_name_plural': 'slaveStatistic信息',
                'db_table': 'slaveStatistic',
            },
        ),
    ]
